### PR TITLE
Proper intro section for tooltip

### PR DESCRIPTION
**Pull request by surma**
Like #94 but for tooltip :)

### CODE REVIEW

**Comment by robdodson** [comment]
This LGTM. Though I'm now definitely thinking that we should extract some of the common guide bits into a separate doc because it's going to be difficult if we want to update the language in one, to have to go to each guide and update it there as well.

**Comment by surma** [comment]
Agreed. Let’s do that when you get back. We can launch these two elements separately for now :)

I’ll make adjustments according to the changes we made to your PR

**Comment by robdodson** [comment]
sgtm!

**Comment by surma** [comment]
WOOOOO 🎉

**Pull request merged**
