### PR TITLE
Add ShadyCSS to howto-checkbox

### PR DESCRIPTION
**Pull request by robdodson**
@surma PTAL

### CODE REVIEW

**Comment by surma** [comment]
I added support for hiding pieces of code with (cc @devnook as an FYI)

```
// HIDE
... this code will be hidden in listings
// /HIDE
```

However, the checkbox demo does not work in FF for me. @robdodson can you take a look?

**Comment by robdodson** [comment]
Works for me...

image

**Comment by surma** [comment]
Then feel free to merge from my side :D

**Comment by robdodson** [comment]
merged, thank you!

**Pull request merged**
