### PR TITLE
Streamline Tooltip

### PR DESCRIPTION
**Pull request by surma**
PTAL!

When merged, set a checkmark in #55, #57 and #85

### CODE REVIEW

**Comment by surma** [comment]
PS: Yes, I removed the animation for simplicities sake for now. I’ll do another PR for animations once we are in a better state universally.

**Comment by robdodson** [comment]
small thing, can you wrap the `return` on line 46? Otherwise LGTM. Merge at your leisure ⛵️

**Comment by surma** [comment]
>  can you wrap the return on line 46? 

Yes. I’ll also see if I can add that to eslint

**Comment by surma** [comment]
Found the rule, will make separate commit!

**Pull request merged**
