### PR TITLE
<howto-slider>

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
Hey @sendilkumarn thanks for sending this in! I'm in a meeting for most of tomorrow so it might take me a couple of days to do a full review but I've started looking into it. I'll follow up as soon as I can.

**Comment by robdodson** [comment]
I think the slider will need to support being dragged by the mouse. If you take a look at this example https://www.w3.org/TR/wai-aria-practices-1.1/examples/slider/slider-1.html I think they have the javascript example which shows how to implement that.

**Comment by sendilkumarn** [comment]
I have done the mouse actions

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
Created a new PR to track this over in #131

**Pull request closed without merging**
